### ISSUE TITLE
Rename tests with same names in lesson11

### ISSUE THREAD

**Issue by mglukhikh** [Kotlin-Polytech/KotlinAsFirst#108]
Kotoed counts same tests as tests for the same task, so requires all of them to pass to add score for this task. Example: sub 38035 from year 2021, see Polynom tasks with 6/8 Tag.

**Comment by ice-phoenix** [comment]
2f4c3f6d2070a66d82ec3a304458a17dccd3a59c kinda did it, did I miss something? )))

**Comment by mglukhikh** [comment]
Great! Probably no.
