### ISSUE TITLE
Clarify lesson7.task2.rotate

### ISSUE THREAD

**Issue by gagarski** [Kotlin-Polytech/KotlinAsFirst#30]
Should we rotate matrix in-place or return a copy?

**Comment by mglukhikh** [comment]
I think both ways are generally possible.

**Comment by gagarski** [comment]
So should we say it explicitly in the task or left it as it is?

**Comment by mglukhikh** [comment]
May be explicitly say is a bit better, but I'm not sure it's really important.

**Comment by mglukhikh** [comment]
I just don't remember some real problems related to this questions (during autumn 2017). If we had them, then it's better to fix this issue.

**Comment by gagarski** [comment]
Does not seem important.
