### ISSUE TITLE
factorizeToString: divisors order

### ISSUE THREAD

**Issue by gagarski** [Kotlin-Polytech/KotlinAsFirst#35]
Clarify that divisros in `factorizeToString` should be in ascending order.

**Comment by evgenykuzin** [comment]
Здравствуйте, помогите пожалуйста разобраться в idea. В файле pom.xml красные подчеркивания и надпись “Expecting a top level declaration”. Не могу из-за этого комитить и пушить.



Отправлено из Почты для Windows 10

От: Kirill Gagarski
Отправлено: 22 ноября 2017 г. в 16:36
Кому: Kotlin-Polytech/KotlinAsFirst
Копия: Subscribed
Тема: [Kotlin-Polytech/KotlinAsFirst] factorizeToString: divisors order(#35)

Clarify that divisros in factorizeToString should be in ascending order.
