### ISSUE TITLE
Add leading zeroes to lesson numbers

### ISSUE THREAD

**Issue by gagarski** [Kotlin-Polytech/KotlinAsFirst#49]
Most directory viewers now sort the lessons as following:

 - lesson1
 - lesson10
 - lesson2
 - lesson3
 - ...
 - lesson9

which is a bit frustrating. 

Adding leading zeroes would solve this problem:

 - lesson01
 - lesson02
 - lesson03
 - ...
 - lesson09
 - lesson10

**Comment by gagarski** [comment]
The other reason to do it is to match the tutorial chapters.

**Comment by mglukhikh** [comment]
Good point

**Comment by mglukhikh** [comment]
(please use milestone 2019 instead of label)

**Comment by mglukhikh** [comment]
Of course it's easy to do, but I'm not sure we should. Pay attention it affects backward compatibility drastically (may be important for Coursera course). If you think it's not important, then let's do it // cc @ice-phoenix

**Comment by gagarski** [comment]
Now we have natural sorting in Kotoed
