### ISSUE TITLE
chapter01: дискриминант

### ISSUE THREAD

**Issue by gagarski** [Kotlin-Polytech/KotlinAsFirst#5]
> Для примера их использования рассмотрим решение задачи вычисления дискриминанта квадратного уравнения. Математически он равен квадратному корню из b<sup>2</sup>-4ac.

Дискриминант равен b<sup>2</sup>-4ac (не корню из), а при вычислении корней используется корень из дискриминанта.

**Comment by gagarski** [comment]
В chapter01 это не влияет на правильность решения, но далее, в chapter02, используется функция discriminant и её возвращаемое значение сравнивается с нулём.  для проверки количества корней. Здесь нужен правильный дискриминант.

**Comment by mglukhikh** [comment]
Ага, спасибо, перепроверю и поправлю.
