### ISSUE TITLE
Migrate to official code style

### ISSUE THREAD

**Issue by mglukhikh** [Kotlin-Polytech/KotlinAsFirst#53]

**Comment by mglukhikh** [comment]
Don't forget to add file with code style settings into repo!

**Comment by gagarski** [comment]
Now IDEA 2019.1 complaints about wrong style somewhere in our code when importing the project from scratch.

![code style](https://i.imgur.com/mALnbd0.png).

This code seems to be properly formatted according to [official code style](https://kotlinlang.org/docs/reference/coding-conventions.html) but there are still warnings. 

When I am trying to adjust it in Idea settings it creates `.idea/codeStyles/Project.xml` file which should probably be commited.

Alternatively we can set flags in `pom.xml` and `build.gradle` as described [here](https://kotlinlang.org/docs/reference/code-style-migration-guide.html). Also it is probably required to make inspections plugin work properly (yet I am not sure).

**Comment by gagarski** [comment]
Follow up:

It seems like Idea use IDE-wise code style settings for this project (obsolete code style probably somehow migrated from my older Idea settings).

It probably won't be a problem for new Idea installations, yet the problem is here: code style config from this project is ignored by Idea.

**Comment by mglukhikh** [comment]
Yes, probably we should set `pom.xml` and `build.gradle` flags.

**Comment by mglukhikh** [comment]
Hope it's fixed now.

**Comment by mglukhikh** [comment]
@gagarski Could you please re-check that everything works as it should?

**Comment by gagarski** [comment]
Yes, now freshly-cloned project works fine.

**Comment by ice-phoenix** [comment]
Flaky behavior of `codeStyles/**.xml` in some cases, needs additional investigation
