### ISSUE TITLE
Add test for sin / cos that will fail with "just sin / cos" solution

### ISSUE THREAD

**Issue by mglukhikh** [Kotlin-Polytech/KotlinAsFirst#66]
Taylor row, for example, should not give exactly the same result as mathematical functions.

**Comment by gagarski** [comment]
I think that explicitly forbidding it in the task description would be enough. Checking that a student result is "not as good" as Math.sin seems bad.

**Comment by mglukhikh** [comment]
I do not agree here. With given precision like `1.0` and angle of `1 rad` we can expect to get exactly `1.0` as an answer and not the `Math.sin` value

**Comment by mglukhikh** [comment]
Also, remember that at Coursera we are unable to check manually do some student obey these rules or not.
