### ISSUE TITLE
Circle.contains and minContainingCircle consistency

### ISSUE THREAD

**Issue by gagarski** [Kotlin-Polytech/KotlinAsFirst#71]
The root of the problem is that `circleByDiameter` does not always `contains` `diameter.begin` and `diameter.end`. 

This can create two bad situations in `minContainingCircle`:
 - `circleByDiameter` is not chosen as minimal because it does not contain `diameter.begin` and `diameter.end`, though it should be minimal
 - if we exclude `diameter.begin` and `diameter.end` from `contains` check we actually get the minimal circle but it does not contain all the `points` in terms of `Circle.contains`

I honestly do not know how to solve it. One way would be to implement #68. The other would be to add explicit hints about consistency for `contains` and `minContainingCircle`.

**Comment by gagarski** [comment]
It seems like choosing the point furthest from center to calculate the radius in `circleByDiameter` solves the problem, however this is quite confusing: both points should have the same distance to center.

**Comment by mglukhikh** [comment]
As an alternative solution, see also #68 (lesson8.task1.Hex). I suggest just to reject the issue, so the students who do not want to struggle with Doubles could struggle with Hexes instead. Or you can add explicit hints about consistency you suggest above. // cc @gagarski

**Comment by mglukhikh** [comment]
I'm closing this issue as "unclear".
