### ISSUE TITLE
Migrate the tasks and infrastructure to kotlin 1.3.41

### ISSUE THREAD

**Issue by belyaev-mikhail** [Kotlin-Polytech/KotlinAsFirst#79]
- KotlinAsFirst
- Random tests (major change)
- Test runner
- Test runner plugins (maven, gradle?)

**Comment by belyaev-mikhail** [comment]
Why migrating random tests is a major change: there is a new version of kcheck with shrinking, which is very desirable for us.

**Comment by mglukhikh** [comment]
I think the target version should be 1.3.41, it's already available.

**Comment by mglukhikh** [comment]
I migrated base repository to 1.3.41 and fixed some style warnings, but no more yet.
