### ISSUE TITLE
Specify task description for top20Words in 7 lesson

### ISSUE THREAD

**Issue by AbdullinAM** [Kotlin-Polytech/KotlinAsFirst#88]
Task description should specify what to do in the situations when there is more than one word for 20th position in the result map

**Comment by mglukhikh** [comment]
I removed 2019.2 milestone because it's not possible to change project which is already forked by a lot of students. About the problem itself, I think we should find 21st, 22nd, etc. words in case there are the same numbers of them as for 20th position.
