### ISSUE TITLE
Check alignFileByWidth tests

### ISSUE THREAD

**Issue by mglukhikh** [Kotlin-Polytech/KotlinAsFirst#95]
Cite from Coursera: 

У вас в тесте к этой задаче ошибка, тест не соответствует второму правилу: "Пустые строки или строки из пробелов трансформируются в пустые строки без пробелов."

**Comment by gagarski** [comment]
I've checked it and cannot see anything wrong: for every blank line in the [input file](https://github.com/Kotlin-Polytech/KotlinAsFirst/blob/master/input/width_in1.txt) there is an empty line in the [expected value](https://github.com/Kotlin-Polytech/KotlinAsFirst/blame/master/test/lesson7/task1/Tests.kt#L126-L143)
